---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
    - recipe[apt]
    - recipe[chef-solo-search]

suites:
- name: default
  run_list:
    - recipe[margarine]
  attributes: {}

- name: tinge
  run_list:
    - recipe[margarine::tinge]
  attributes: {}

- name: blend
  run_list:
    - recipe[margarine::blend]
  attributes: {}

- name: spread
  run_list:
    - recipe[margarine::spread]
  attributes: {}
