---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.4
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

suites:
- name: blend
  run_list:
    - recipe[margarine]
  attributes:
    margarine:
      components: ["blend"]

- name: blend_and_spread
  run_list:
    - recipe[margarine]
  attributes:
    margarine:
      components: ["blend", "spread"]

- name: spread
  run_list:
    - recipe[margarine]
  attributes:
    margarine:
      components: ["spread"]
